let text = [
    "Esta historia tiene como personaje principal a Tim, un chico alto, delgado y pelirrojo. Tim vive con sus padres, su tio y su hermana menor llamada Kit Kat. Tim no era muy bueno con las chicas. Su familia realizó una fiesta para año nuevo, invitando a muchos amigos y  familiares. Llegado la media noche, todas las personas se besaron con alguien, a excepción de Tim. Había una chica que quería ser besada por Tim, pero Tim solamente le dio la mano.",
    "El padre de Tim lo llama, quería tener una charla con el. Su padre le revela que los varones de su familia obtienen el don de poder viajar en el tiempo cuando cumplen  21 años. Tim al principio pensó que era una broma, pero su padre lo convenció de intentarlo. El proceso era muy simple, solamente debía de ir a un lugar oscuro y solitario, apretar los puños y pensar a que momento, de su vida, quería regresar.\n Tim se metió en un armario, apretó los puños y viajó en el tiempo, más concretamente a la nocheanterior. Entonces Tim sin dudarlo hizo las cosas correctamente, besó a la chica y regresó al presente como todo un ganador.\nAl ver que era cierto, regresó con su padre para seguir charlando. Este le dijo que no vale la pena usar este poder para conseguir dinero o poder, que al final se quedaría solo,como le pasó a un familiar suyo. Entonces Tim pensó en utilizar este poder para poder conseguiruna novia.",
    "El verano de ese año, llegó la prima de Jimmy (novio de Kit Kat) llamada Charlotte. Tim se enamoró de ella a primera vista. Así que siguiendo el consejo que le dio su padre, utilizarálos viajes en el tiempo para convertirse en su novio. Gracias a esto logró demostrar en multiples ocasiones que es una persona lista, interesante y atlética. Al final del verano, Tim le declaró su amor a Charlotte, pero ella lo rechazó diciendo que no fue buena idea haberle pedido eso justo en la última noche en la que ella iba a estar con ellos. Entonces a Timse le ocurrió viajar en el tiempo a la mitad del verano para declararle su amor, pero esta vez Charlotte le dijo que mejor esperen hasta fin del verano para ver como irian las cosas. Tim se decepcionó de esto, pero aprendió una valiosa lección. Algunas cosas no se pueden cambiar por más veces que uno viaje en el tiempo.",
    "Un dia despues, Tim se marchó a Londres para seguir con su carrera de abogado. Se mudó con un amigo de su padre llamado Harry, quien hace obras de teatro. En el trabajo se hace amigo de su compañero Rory. Durante mucho tiempo, Tim no conoció a ninguna chica, todo el tiempo la pasaba solo o acompañado de Rory. Un día, su mejor amigo llamado Jay lo invita a una cita a ciegas, allí Tim conoce a una mujer llamada Mary. Hablan durante un par de horas. Cuando Mary ya se tenía que marchar, le dió su numero para que pudieran salir algún día. Tim se emocionó, pero al llegar a su casa, se encontró que Harry habia tenido la peor noche de su vida, ya que esa noche iba a presentar la mejor obra que habia hecho hasta ese momento, pero en la presentación, un actor olvidó sus líneas en la parte más importante.Gracias a esto, la obra de Harry fue todo un desastre. Tim decide hecharle una mano y viaja en el tiempo para hacer que el actor no olvide sus líneas. Lo consigue y hace que la obra de Harry sea un exito. Luego de la obra, Tim intenta contactar con Mary, pero se percata que gracias a que ayudó a Harry, el nunca fue a la cita a ciegas y nunca conoció a Mary. Tim se deprime, ya que vuelve a estar solo. ",
    "Al día siguiente Tim se percató que en el periódico decía que habría una exhibición de Kate Moss (Durante la cita a ciegas, Mary dijo que le encantaba Kate Moss), entonces decide ir a la exhibición para encontrarla.Pasaron algunos días y Tim la ve. Se le acerca a hablarle, pero la termina asustando al principio. Despues de unos minutos de estar charlando, Tim descubre que Mary tiene un novio, lo conoció hace un par dedías. Tim trata de descubrir en donde y cuando se conocieron. Ellos se conocieron en una fiesta. Entonces Tim decide viajar en el tiempo e ir a la fiesta. Tim ve a Mary en la fiesta, aburrida,entonces decide acercarse a hablarle. Pasan algunos minutos y Tim propone la idea de ir a otro lugar, ya que la fiesta parecia aburrida. Mary acepta y se van. Pasan una velada agradable. Los dos descubren que tienen gustos muy similares. La noche pasa y ellos se convierten en pareja.",
    "Tim y Mary llevan mucho tiempo siendo pareja. Un día Tim obtiene dos boletos para ir al teatro. Mary no quiere ir, prefiere quedarse dormida todo el día, ya que es su día de descanso, entonces Tim decide ir con Rory. Ya al haber terminado la obra, Tim ve entre el público a Charlotte que estaba acompañada por una amiga. Tim decide acercarse a hablar, pero termina diciendo algo indebido y decide viajar en el tiempo para arreglarlo. Vuelve a meter la mata y decide viajar otra vez, pero esta vez evitando a Charlotte. Saliendo del teatro, Charlotte ve a Tim y se acerca a hablarle. Charlotte invita a Tim a un restaurante para seguir charlando. Luego de la cena Tim acompaña a Charlotte hasta su hotel. Charlotte se le declara a Tim y lo invita a pasar a su habitación, pero este se niega, ya que se da cuenta que con la única persona que quiere estar el resto de su vida es con Mary. Luego se vuelve hacia su departamento y le pide matrimonio a Mary. Aunque termina arruinando las cosas ya que despierta a Mary de una forma brusca y esta se levanta de mal humor. Lo vuelve a intentar, pero esta vez más calmado. Mary acepta.\nPasan unos meses y se realiza la boda. Unos meses despues de la boda nace la primera hija de Tim. Tim ya tiene todo lo que deseaba para ser feliz y considera que llegado hasta ese punto, ya no es necesario viajar en el tiempo.",
    "Es el cumpleaños de la hija de Tim. Toda su familia esta reunida a excepción de Kit Kat. Luego de un rato, llega solamente el novio de Kit Kat, Jimmy. Tim le pregunta que donde estasu hermana. Este le responde que tuvieron una pelea en la mañana y que ella a estado bebiendo. Luego Tim recibe una llamada donde le informan que Kit Kat sufrió un accidentepor manejar tomada. Tim decide viajar en el tiempo e ir por Kit Kat, evitando el accidente. Tim se da cuenta que Kit Kat no es feliz con la vida que tiene. No tieneun trabajo estable y su relación con Jimmy no es saludable. Entonces Tim le revela a Kit Kat que el puede viajar en el tiempo y deciden ir a la fiesta de año nuevo, dondeKit Kat conoció a Jimmy. Tim le muestra que Jimmy no vale la pena. Sí Kit Kat no lo hubiera conocido, este se hubiera ido con cualquier otra chica. Entonces regresan al presentey Kit Kat se convirtió en la novia de Jay. Tim se da cuenta que Kit Kat tiene una mejor vida con Jay y decide regresar a su casa. Estando de regreso, Tim decide ir a ver a su hija, pero se percata que ya no esta su hija, en su lugar hay otro niño. Entonces Tim viaja al día del nacimiento de su hija y le pregunta a su padre que porque tiene a otro niño como hijo.Este le menciona que no puede viajar antes del nacimiento de un hijo, ya que se deben de cumplir las condiciones exactas para que su hija nazca. Entonces Tim regresa las cosas a como estaban en un principio.En el hospital, Tim y Mary deciden hablar con Kit Kat y hacerle entender que debe de dejar a Jimmy y buscar a alguien más. Toma un tiempo, pero Kit Kat lo entiende. Tim le sugiere que salga conJay. Kit Kat decide seguir su consejo. Pasa el tiempo y Kit Kat tiene una mejor vida con Jay.",
    "Pasa el tiempo, Tim tiene otro hijo. Era un día cualquiera, Tim recibe una llamada de su madre. El padre de Tim tiene cancer. Tim viaja hasta la casa de sus padres y tiene una conversación con su padre.Su padre le dice que le dio cancer por haber fumado en su juventud. El no puede arreglarlo porque fue antes de que Tim naciera. Luego su padre le revela el mayor secreto de los viajes en el tiempo. El secreto consiste en como disfrutar la vida. El primer paso consiste en vivir un día normal, con las preocupaciones, tensiones que hay en un día y el segundo paso consiste en volver al inicio de ese día, pero esta vez disfrutando cada momento del día. Disfrutando hasta el más mínimo detalle. Tim lo puso a prueba y al vivir otra vez ese mismo día se percató de muchas cosas que una persona se pierde por estar concentrado en otras cosas. Luego llegó el día. En palabras de Tim Hay algunos días que a nadie le gustaría volver a repetir, pero Tim aún quería seguir pasando tiempo con su padre. Gracias a los viajes en el tiempo, Tim aún puede seguir viendo a su padre a pesar de que esta ya haya muerto. Así lo estuvo haciendo durante muchos días. Hasta que un díaMary le mencionó la idea a Tim sobre tener otro hijo. Tim al principio se vió dudoso, ya que al tener otro hijo, ya no podrá ver a su padre. Tim al final aceptó, ya que debía de dejar el pasado y de seguir con el futuro. Antes de que naciera su tercer hijo, Tim decide visitar a su padre por última vez. Juegan un partido de tennis de mesa. Su padre gana y le pregunta cual es su premio. Tim le dice que es un beso. Su padre al inicio se ve un poco confundido, pero termina entendiendo que es la despedida. Así que le pide a Tim un último obsequio. Le pide dar una paseo por la playa, pero viajando unos años más atras, donde Tim es un niño y su padre es más joven. Tim le pregunta si estará bien hacer eso y su padre le responde que si son cuidadosos, no cambiaran nada.Y así es, viajan al pasado y tienen un último paseo por la playa.",
    "Ya han pasado varios años, Tim menciona que ha logrado aprender mucho más que su padre sobre los viajes en el tiempo. La lección que aprendió Tim es vivir cada día de tu vida como si fuera el último, no es necesario vivir un día dos veces para poder disfrutarlo. Y así es, Tim vive cada día de su vida como si fuera la segunda vezque lo vive. Disfrutando hasta el más mínimo detalle."
]
let title = [
    "Inicio",
    "Un don",
    "Algunas cosas no se pueden cambiar",
    "Un día cualquiera",
    "Una nueva oportunida",
    "La felicidad",
    "Para un problema existen varias soluciones",
    "Algunos días es mejor solo vivirlos una vez",
    "Vivir cada día como si fuera el último"
]
window.onload = function (){
    var pagina = localStorage.getItem("numero");  
    if (pagina !== null){
        document.getElementById("titulo").innerHTML = title[pagina - 1];
        document.getElementById("historia").innerHTML = text[pagina - 1];
        window.localStorage.clear();
    }else {
        document.getElementById("titulo").innerHTML = title[0];
        document.getElementById("historia").innerHTML = text[0];
        window.localStorage.clear();
    }
}


var page = (pagina) => {
    document.getElementById("titulo").innerHTML = title[pagina - 1];
    document.getElementById("historia").innerHTML = text[pagina - 1];
}

const bar = "hola"
const saludo = "    hola amigo".trimStart();
`foo${bar}`;
